### ISSUE TITLE
Sharing iP code quality feedback [for @yucongkoo]

### ISSUE THREAD

**Issue by nus-se-script** [yucongkoo/ip#3]
@yucongkoo We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/duke/TaskManager.java` lines `114-114`](https://github.com/yucongkoo/ip/blob/7bc965edfd96f4d12317114f68b2d53cfd65b733/src/main/java/duke/TaskManager.java#L114..L114):

```java

        boolean found = false;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/duke/Main.java` lines `17-17`](https://github.com/yucongkoo/ip/blob/7bc965edfd96f4d12317114f68b2d53cfd65b733/src/main/java/duke/Main.java#L17..L17):

```java

    // private Duke duke = new Duke("data", "tasks.json");

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/gui/MainWindow.java` lines `62-65`](https://github.com/yucongkoo/ip/blob/7bc965edfd96f4d12317114f68b2d53cfd65b733/src/main/java/gui/MainWindow.java#L62..L65):

```java

    /**
     * You should have your own function to generate a response to user input.
     * Replace this stub with your completed method.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by yucongkoo** [comment]
Resolved.
